name: video_player_videohole_example
description: Demonstrates how to use the video_player_videohole plugin.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  video_player_plusplayer:
    path: ../video_player_plusplayer

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
